config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :bloggers do
  	resources :comments 
  end
  resources :comments do
        resources :replies
  end
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blogger.rb
class Blogger < ApplicationRecord
	   has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blogger
  has_many :replies
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :blogger
  belongs_to :comment
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/bloggers_controller.rb
class BloggersController < ApplicationController
    def index
    @bloggers = Blogger.all
  end
 
  def show
    @blogger = Blogger.find(params[:id])
  end
 
  def new
    @blogger = Blogger.new
  end
 
  def edit
    @blogger = Blogger.find(params[:id])
  end
 
  def create
    @blogger = Blogger.new(blogger_params)
 
    if @blogger.save
      redirect_to @blogger
    else
      render 'new'
    end
  end
 
  def update
    @blogger = Blogger.find(params[:id])
 
    if @blogger.update(blogger_params)
      redirect_to @blogger
    else
      render 'edit'
    end
  end
 
  def destroy
    @blogger = Blogger.find(params[:id])
    @blogger.destroy
 
    redirect_to bloggers_path
  end
 
  private
    def blogger_params
      params.require(:blogger).permit(:title, :text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    @blogger = Blogger.find(params[:blogger_id])
    @comment = @blogger.comments.create(comment_params)
    redirect_to blogger_path(@blogger)
  end
 
  def destroy
    @blogger = Blogger.find(params[:blogger_id])
    @comment = @blogger.comments.find(params[:id])
    @comment.destroy
    redirect_to blogger_path(@blogger)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
	def create

    
    @reply = Reply.new(:body=>params[:reply][:body],:commen_id=>params[:reply][:comment_id])
    @reply.save
    flash[:notice]= "replies created"
    redirect_to "/bloggers/#{params[:blogger_id]}"
    
  end
  
  def new
   @reply = Reply.new
  end
 
  # def destroy
  #   @blogger = Blogger.find(params[:blogger_id])
  #   @comment = @blogger.comments.find(params[:id])
  #   @comment.destroy
  #   redirect_to blogger_path(@blogger)
  # end
 
  private
    def reply_params
      params.require(:reply).permit(:comment_id, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bloggers_helper.rb
module BloggersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bloggers/_form.hml.erb
 <strong>Title:</strong>
  <%= @blogger.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @blogger.text %>
</p>
 
<h2>Comments</h2>
<%= render @blogger.comments %>
 
 
<%= link_to 'Edit', edit_blogger_path(@blogger) %> |
<%= link_to 'Back', bloggers_path %>

app/views/bloggers/edit.html.erb
<h1>Edit blogger</h1>
 
<%= form_with(model: @blogger, local: true) do |form| %>
 
  <% if @blogger.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@blogger.errors.count, "error") %> prohibited
        this blogger from being saved:
      </h2>
      <ul>
        <% @blogger.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

 

<%= link_to 'Back', bloggers_path %>

app/views/bloggers/index.html.erb
<h1>Listing bloggers</h1>
<%= link_to 'new blog', new_blogger_path(@blogger) %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="2"></th>
  </tr>
 
  <% @bloggers.each do |blogger| %>
    <tr>
      <td><%= blogger.title %></td>
      <td><%= blogger.text %></td>
      <td><%= link_to 'Show', blogger_path(blogger) %></td>
      <td><%= link_to 'Edit', edit_blogger_path(blogger) %></td>
      <td><%= link_to 'Destroy', blogger_path(blogger),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/bloggers/new.html.erb
<%= form_with scope: :blogger, url: bloggers_path, local: true do |form| %>
 
  <% if @blogger.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@blogger.errors.count, "error") %> prohibited
        this blogger from being saved:
      </h2>
      <ul>
        <% @blogger.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

 
<%= link_to 'Back', bloggers_path %>

app/views/bloggers/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @blogger.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @blogger.text %>
</p>
 
<h2>Comments</h2>
<%= render @blogger.comments %>
 
<h2>Add a comment:</h2>
<%= form_with(model: [ @blogger, @blogger.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
 
<%= link_to 'Edit', edit_blogger_path(@blogger) %> |
<%= link_to 'Back', bloggers_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

	<%#= link_to 'Reply', new_blogger_comment_reply_path(comment.blogger, comment) %> 
  <%= render "replies/form",comment: comment %>
  <%= link_to 'Destroy Comment', [comment.blogger, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>
<div
id="user_nav">
 <% if user_signed_in? %> Signed in as <%= current_user.email %>.Not you?
<%= link_to "Sign out", destroy_user_session_path, :method=> :delete %>
<% else %>
<%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
<% end %>
</div>

app/views/replies/_form.html.erb
<%= form_for([comment, Reply.new]) do |f| %>
<%= f.hidden_field :comment_id, :value=> comment.id %> 
<%= f.text_field :body %> 
<%= f.submit "Reply" %>
<% end %>

app/views/replies/_reply.html.erb
 
<p>
  <strong>Reply:</strong>
  <%= reply.body %>
</p>


<p>
  <%= link_to 'Destroy Reply', [comment.blogger, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/replies/new.html.erb
<%= render 'form', blogger: @blogger, comment: @comment, reply: @reply %>

app/views/welcome/index.html.erb
  <div class="header">
  <a href="#default" class="logo">blogLogo</a>
  <div class="header-right">
    <a class="active" href="bloggers">blogger</a>
    <a href="#contact">Contact</a>
    <a href="#about">About</a>
  </div>
</div> 
<%= link_to 'My Blog', controller: 'bloggers' %>